[package]
name = "rmf-core"
version.workspace = true
edition.workspace = true
authors.workspace = true


[dev-dependencies]
rstest.workspace = true
pretty_assertions.workspace = true

[dependencies]
derive-new.workspace = true
thiserror.workspace = true
