[package]
name = "rmf-host"
version.workspace = true
authors.workspace = true
edition.workspace = true
license-file.workspace = true

[dependencies]
rmf-static = { path = "../rmf-static" }
rmf-core = { path = "../rmf-core" }
thiserror.workspace = true
derive-new.workspace = true
