[package]
name = "rmft"
version.workspace = true
authors.workspace = true
edition.workspace = true
license-file.workspace = true

[dependencies]
anyhow.workspace = true
eframe = "0.33.3"
rmf-host = { path = "../../frameworks/rmf-host" }
tokio = { version = "1.48.0", features = ["time", "sync", "rt"] }
