name: test

on:
  push:
  pull_request:

jobs:
  cargo-test-per-feature:
    strategy:
      matrix:
        feature: ["default","rmf-static/default_link_static_dependencies"]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/qwerty2501/rmf/ci_test:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: cargo test
        run: cargo test --features ${{ matrix.feature }} --verbose
      - name: cargo build
        run: cargo build --features ${{ matrix.feature }} --release --verbose

  cargo-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/qwerty2501/rmf/ci_test:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: cargo lint
        run: cargo lint
      - name: cargo fmt
        run: cargo fmt --check

  cspell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: streetsidesoftware/cspell-action@v8
